import {StyleSheet} from 'react-native';

export const globalStyles = StyleSheet.create({
  buttonContainer: {
    width: 270,
    backgroundColor: '#AE0000',
    padding: 10,
    margin: 5,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    fontSize: 20,
    fontWeight: '500',
    color: '#fff',
  },
  buttonWrapper: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    bottom: 30,
    left: 0,
    right: 0,
    borderRadius: 10,
  },
  textInput: {
    height: 50,
    borderRadius: 10,
    borderColor: '#ddd',
    borderWidth: 1,
    margin: 10,
    padding: 5,
  },
  modalStyle: {
    flex: 1,
    backgroundColor: '#000000ee',
    justifyContent: 'center',
  },
  modalContainer: {
    marginHorizontal: 40,
    marginVertical: 100,
    borderRadius: 20,
    backgroundColor: '#fff',
  },
  listItemContainer: {
    padding: 10,
    margin: 10,
    backgroundColor: 'white',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#ddd',
    elevation: 3,
  },
  listItemContent: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  listItemIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    padding: 10,
    margin: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mediumText: {
    fontSize: 16,
    fontWeight: '500',
  },
  absoluteCenter: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    top: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  absoluteBottom: {position: 'absolute', bottom: 30, left: 0, right: 0},
  headerContainer: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerContent: {
    flexDirection: 'row',
    height: 56,
    padding: 10,
    marginHorizontal: 10,
    alignItems: 'center',
  },
  headerText: {fontSize: 24, fontWeight: '600'},
  errorMessageContainer: {marginLeft: 10, marginTop: -5},
  errorMessageText: {color: '#df4759'},
});
